Repository js-org/js.org, pull requests merged in 2018-06, with the labels that each got.

#2046 marvnet.js.org
  cnames_active.js
Labels: add, organisation, project, provisional content

#2047 sistersbio.js.org
  cnames_active.js
Labels: add, project, user

#2050 sheet.js.org
  cnames_active.js
Labels: add, organisation, project

#2048 single-spa.js.org
  cnames_active.js
Labels: add, organisation, project

#2051 meshesha.js.org
  cnames_active.js
Labels: add, user

#2052 flying-squid.prismarine.js.org
  cnames_active.js
Labels: add, organisation, project

#2054 mineflayer.prismarine.js.org
  cnames_active.js
Labels: add, organisation, project

#2049 vuetify-sidebar-template.js.org
  cnames_active.js
Labels: add, project, user

#2062 cookiebox.js.org
  cnames_active.js
Labels: add, project, user

#2057 rayo.js.org
  cnames_active.js
Labels: add, organisation, project

#2060 reshape.js.org
  cnames_active.js
Labels: add, external page

#2061 spike.js.org
  cnames_active.js
Labels: add, external page

#2065 get.js.org
  cnames_active.js
Labels: add, organisation, project

#2056 epoxy.js.org
  cnames_active.js
Labels: add, external page

#2066 materialish.js.org
  cnames_active.js
Labels: add, project, user

#2064 cookiebox.js.org
  cnames_active.js
Labels: change, external page, invalid, organisation, project

#2068 pwa-workshop.js.org
  cnames_active.js
Labels: add, project, user

#2069 floffan.js.org
  cnames_active.js
Labels: add, project, user

#2070 mahmoud.js.org
  cnames_active.js
Labels: add, project, provisional content, user

#2071 miscord.js.org
  cnames_active.js
Labels: change, project, user

#2072 ciphercrack.js.org
  cnames_active.js
Labels: add, project, user

#2073 docsify.js.org
  cnames_active.js
Labels: change, organisation, project, user

#2067 pptx.js.org
  cnames_active.js
Labels: add, project, user

#2074 ghapi.js.org
  cnames_active.js
Labels: add, project, user

#2075 awesome-vue.js.org
  cnames_active.js
Labels: add, project, user

#2076 manytimepad.js.org
  cnames_active.js
Labels: add, project, user

#2079 canvasconstructor.js.org
  cnames_active.js
Labels: change, project

#2081 leet.js.org
  cnames_active.js
Labels: add, user

#2077 officetohtml.js.org
  cnames_active.js
Labels: add, project, user

#2083 nfwyst.js.org
  cnames_active.js
Labels: add, user

#2087 lava.js.org
  cnames_active.js
Labels: add, organisation, project

#2088 alys.js.org
  cnames_active.js
Labels: add, project, user

#2091 hugorocaproyectos.js.org
  cnames_active.js
Labels: add, project, user

#2089 polix.js.org
  cnames_active.js
Labels: add, project, user

#2092 vssue.js.org
  cnames_active.js
Labels: add, project, user

#2093 gitme.js.org
  cnames_active.js
Labels: add, project, user

#2094 redux-saga-firebase.js.org
  cnames_active.js
Labels: add, external page

#2095 yvm.js.org
  cnames_active.js
Labels: add, external page

#2096 iot.js.org
  cnames_active.js
Labels: add, organisation, project

#2097 smox.js.org
  cnames_active.js
Labels: add, project, user

#2098 unicornly.js.org
  cnames_active.js
Labels: add, organisation, project

#2100 iiilfaaa.js.org
  cnames_active.js
Labels: add, provisional content, user

#2102 player.js.org
  cnames_active.js
Labels: add, project, user

#2103 replace.js.org
  cnames_active.js
Labels: add, project, user

#2106 secsb.js.org
  cnames_active.js
Labels: add, user

#2107 arthurmbandeira.js.org
  cnames_active.js
Labels: add, user
