Repository js-org/js.org, pull requests merged in 2018-11, with the labels that each got.

#2482 srvr.js.org
  cnames_active.js
Labels: add, organisation, project

#2483 dtps.js.org
  cnames_active.js
Labels: add, project, user

#2485 reactif.js.org
  cnames_active.js
Labels: add, project, user

#2486 sawyer.js.org
  cnames_active.js
Labels: add, project, user

#2488 split.js.org
  cnames_active.js
Labels: change, project, user

#2487 project-ignite.js.org
  cnames_active.js
Labels: add, organisation, project

#2489 wglt.js.org
  cnames_active.js
Labels: add, project, user

#2493 naja.js.org
  cnames_active.js
Labels: add, project, user

#2495 mojiscript.js.org
  cnames_active.js
Labels: add, project, user

#2496 matrix-rref-solver.js.org
  cnames_active.js
Labels: add, project, user

#2497 framework.js.org
  cnames_active.js
Labels: add, organisation, project

#2498 fallr.js.org
  cnames_active.js
Labels: add, project, user

#2499 promise.js.org
  cnames_active.js
Labels: add, user

#2500 futch.js.org
  cnames_active.js
Labels: add, project, user

#2503 19cah.js.org
  cnames_active.js
Labels: project, remove, user

#2505 george.js.org
  cnames_active.js
Labels: add, project, user

#2509 jamal.js.org
  cnames_active.js
Labels: add, project, user

#2507 ahmad.js.org
  cnames_active.js
Labels: add, project, user

#2513 hybrids.js.org
  cnames_active.js
Labels: add, external page

#2516 audio-stream.js.org
  cnames_active.js
Labels: add, invalid, project, user

#2521 mzplayer.js.org
  cnames_active.js
Labels: add, project, user

#2522 neotidev.js.org
  cnames_active.js
Labels: change, project, user

#2524 particledb.js.org
  cnames_active.js
Labels: add, project, user

#2528 ewa.js.org
  cnames_active.js
Labels: add, project, user

#2529 iori.js.org
  cnames_active.js
Labels: add, user

#2532 ps.js.org
  cnames_active.js
Labels: add, project, user

#2530 jamal.js.org
  cnames_active.js
Labels: change, organisation, project

#2534 warship.js.org
  cnames_active.js
Labels: add, project, user

#2537 awesome-nuxt.js.org
  cnames_active.js
Labels: add, project, user

#2541 sanity-runner.js.org
  cnames_active.js
Labels: add, organisation, project

#2544 yajdbl.js.org
  cnames_active.js
Labels: add, project, user

#2545 JS.ORG CLEANUP
  cnames_active.js
Labels: remove

#2546 passepartout.js.org
  cnames_active.js
Labels: add, project, user

#2548 clabe-validator.js.org
  cnames_active.js
Labels: add, organisation, project

#2549 soundpad.js.org
  cnames_active.js
Labels: add, project, user

#2539 tuplerone.js.org
  cnames_active.js
Labels: add, project, user

#2550 lego.js.org
  cnames_active.js
Labels: add, organisation, project

#2552 vrv.js.org
  cnames_active.js
Labels: add, project, user

#2554 common-utils-pkg.js.org
  cnames_active.js
Labels: change, project, user

#2553 soroush.js.org
  cnames_active.js
Labels: add, user

#2556 currency.js
  cnames_active.js
Labels: add, project, user

#2558 omid.js.org
  cnames_active.js
Labels: add, user

#2557 vrv.js.org
  cnames_active.js
Labels: change, external page

#2561 anna.js.org
  cnames_active.js
Labels: add, user

#2562 webpack-config-plugins.js.org
  cnames_active.js
Labels: add, organisation, project

#2563 ng-app.js.org
  cnames_active.js
Labels: add, project, user
