Repository js-org/js.org, pull requests merged in 2018-04, with the labels that each got.

#1879 guppy.js.org
  cnames_active.js
Labels: add, project, user

#1870 andre.js.org
  cnames_active.js
Labels: change, user

#1881 react-through.js.org
  cnames_active.js
Labels: add, project, user

#1882 ralphi.js.org / hapi-sol.js.org
  cnames_active.js
Labels: add, project, user

#1886 notice.js.org
  cnames_active.js
Labels: add, project, user

#1887 stampit.js.org
  cnames_active.js
Labels: add, external page

#1885 react-through.js.org
  cnames_active.js
Labels: change, external page, project, user

#1883 just.js.org
  cnames_active.js
Labels: add, user

#1888 hubble.js.org
  cnames_active.js
Labels: add, project, user

#1895 nuxtdoc.js.org
  cnames_active.js
Labels: add, external page

#1893 vue-core.js.org
  cnames_active.js
Labels: add, organisation, project

#1897 blessmyrains.js.org
  cnames_active.js
Labels: add, project, user

#1901 rsshub.js.org
  cnames_active.js
Labels: add, project, user

#1894 active-resource.js.org
  cnames_active.js
Labels: add, project, user

#1903 jk.js.org
  cnames_active.js
Labels: add, user

#1904 john.js.org
  cnames_active.js
Labels: add, user

#1909 danieljuarezp.js.org
  cnames_active.js
Labels: change, project, user

#1908 fidel.js.org
  cnames_active.js
Labels: add, user

#1912 defi.js.org
  cnames_active.js
Labels: add, project, user

#1906 imcvampire.js.org
  cnames_active.js
Labels: add, user

#1911 tmr.js.org
  cnames_active.js
Labels: add, user

#1913 hubble.js.org
  cnames_active.js
Labels: change, external page, project, user

#1910 acebooks.js.org
  cnames_active.js
Labels: add, project, provisional content, user

#1915 poi.js.org
  cnames_active.js
Labels: change, external page, project, user

#1917 cac.js.org
  cnames_active.js
Labels: add, project, user

#1918 potion.js.org
  cnames_active.js
Labels: add, project, user

#1920 styled-icons.js.org
  cnames_active.js
Labels: add, external page

#1914 andre.js.org
  cnames_active.js
Labels: change, user

#1922 metools.js.org
  cnames_active.js
Labels: add, project, user

#1925 otakubot.js.org
  cnames_active.js
Labels: add, project, user

#1928 godzm4tt3o.js.org
  cnames_active.js
Labels: add, user

#1930 verse.js.org
  cnames_active.js
Labels: add, organisation, project

#1931 boilerplates.js.org
  cnames_active.js
Labels: add, project, user

#1934 redux-actions.js.org
  cnames_active.js
Labels: change, external page

#1935 super.js.org
  cnames_active.js
Labels: add, organisation, project

#1933 bigtest.js.org
  cnames_active.js
Labels: organisation, project, remove

#1936 start.js.org
  cnames_active.js
Labels: add, project, provisional content, user

#1939 ajv.js.org
  cnames_active.js
Labels: add, project, user
