Repository js-org/js.org, pull requests merged in 2018-10, with the labels that each got.

#2369 macosnotif.js.org
  cnames_active.js
Labels: SSL, change

#2372 react-solar-datetime-picker.js.org
  cnames_active.js
Labels: project, remove, user

#2370 mysite.js.org
  cnames_active.js
Labels: change, external page, project, provisional content, user

#2376 krunnie.js.org
  cnames_active.js
Labels: add, user

#2373 mo.js.org
  cnames_active.js
Labels: add, project, user

#2374 mysite.js.org
  cnames_active.js
Labels: change, external page, invalid, project, user

#2378 jz.js.org
  cnames_active.js
Labels: add, user

#2382 ha-store.js.org
  cnames_active.js
Labels: add, project, user

#2385 nikmartin.js.org
  cnames_active.js
Labels: add, user

#2386 arda.js.org
  cnames_active.js
Labels: add, user

#2387 erdems.js.org
  cnames_active.js
Labels: add, user

#2388 sanohin.js.org
  cnames_active.js
Labels: add, user

#2383 modulajs.js.org
  cnames_active.js
Labels: add, external page

#2392 redux-dynamic-modules.js.org
  cnames_active.js
Labels: add, organisation, project

#2394 davet.js.org
  cnames_active.js
Labels: add, project, user

#2395 zeit.js.org
  cnames_active.js
Labels: change, user

#2396 perilla.js.org
  cnames_active.js
Labels: add, project, user

#2391 react-redux.js.org
  cnames_active.js
Labels: add, external page

#2390 roadmafia.js.org
  cnames_active.js
Labels: add, project, user

#2389 split.js.org
  cnames_active.js
Labels: add, project, user

#2397 wice.js.org
  cnames_active.js
Labels: add, project, user

#2398 spotix.js.org
  cnames_active.js
Labels: add, project, user

#2402 german.js.org
  cnames_active.js
Labels: add, project, user

#2401 zodiacsigns.js.org
  cnames_active.js
Labels: add, project, user

#2404 li.js.org
  cnames_active.js
Labels: add, project, user

#2405 bara.js.org
  cnames_active.js
Labels: add, organisation, project

#2406 tiza.js.org
  cnames_active.js
Labels: add, project, user

#2416 recover.js.org
  cnames_active.js
Labels: add, project, user

#2418 noCF for djvu.js.org
  cnames_active.js
Labels: SSL, change

#2421 j3n5en.js.org
  cnames_active.js
Labels: add, user

#2423 sutanlab.js.org
  cnames_active.js
Labels: add, project, user

#2424 neotidev.js.org
  cnames_active.js
Labels: add, organisation, project

#2425 mardatonne.js.org
  cnames_active.js
Labels: add, organisation, project

#2426 animals-ascii.js.org
  cnames_active.js
Labels: add, organisation, project

#2417 766.js.org
  cnames_active.js
Labels: add, user

#2400 konstructor.js.org
  cnames_active.js
Labels: external page, remove

#2435 dawn.js.org
  cnames_active.js
Labels: add, project

#2437 https://electron-react-boilerplate.js.org/.js.org
  cnames_active.js
Labels: add, organisation, project

#2440 relaunch.js.org
  cnames_active.js
Labels: add, project, user

#2444 Add retech.js.org for codeindore.github.io/retech
  cnames_active.js
Labels: add, organisation, project

#2443 fucao.js.org
  cnames_active.js
Labels: add, user

#2438 Update pull request template to use checkboxes
  PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#2447 wiki.js.org
  cnames_active.js
Labels: change, external page, organisation, project

#2449 remove mysite.js.org per #2448
  cnames_active.js
Labels: project, remove

#2450 Fix missing commas
  cnames_active.js
Labels: enhancement

#2454 webmetry.js.org
  cnames_active.js
Labels: add, organisation, project

#2459 unified.js.org
  cnames_active.js
Labels: add, organisation, project

#2453 Add contributing guidelines covering common PR issues
  CONTRIBUTING.md
Labels: enhancement

#2467 title.js.org
  cnames_active.js
Labels: add, project, user

#2468 arief.js.org
  cnames_active.js
Labels: add, user

#2470 quinten.js.org
  cnames_active.js
Labels: add, user

#2471 xstate.js.org
  cnames_active.js
Labels: add, project, user

#2472 stino.js.org
  cnames_active.js
Labels: add, user

#2473 ion.js.org
  cnames_active.js
Labels: add, organisation

#2475 virtual-keyboard.js.org
  cnames_active.js
Labels: add, organisation

#2479 yennj12.js.org
  cnames_active.js
Labels: add, user

#2480 popcorn-api.js.org
  cnames_active.js
Labels: add, project, user
