Repository js-org/js.org, pull requests merged in 2018-12, with the labels that each got.

#2570 depo.js.org
  cnames_active.js
Labels: add, project, user

#2572 liuence.js.org
  cnames_active.js
Labels: add, provisional content, user

#2573 concurrent-tasks.js.org
  cnames_active.js
Labels: add, external page, provisional content

#2577 happyae.js.org
  cnames_active.js
Labels: add, user

#2575 cebu.js.org
  cnames_active.js
Labels: add, external page

#2574 quotes.js.org
  cnames_active.js
Labels: add, project, user

#2578 star.js.org
  cnames_active.js
Labels: add, organisation, project

#2571 redux-starter-kit.js.org
  cnames_active.js
Labels: add, external page

#2580 farzad.js.org
  cnames_active.js
Labels: add, project, user

#2582 copyer.js.org
  cnames_active.js
Labels: add, organisation, project

#2590 mohitgupta.js.org
  cnames_active.js
Labels: add, user

#2588 solace.js.org
  cnames_active.js
Labels: add, project, user

#2587 santa.js.org
  cnames_active.js
Labels: add, organisation, project

#2579 creaturegen.js.org
  cnames_active.js
Labels: add, project, user

#2591 Fix master link
  README.md
Labels: enhancement

#2592 eqeq.js.org
  cnames_active.js
Labels: add, project, user

#2595 ppt.js.org
  cnames_active.js
Labels: add, project, user

#2593 redux.js.org
  cnames_active.js
Labels: change, external page, organisation, project

#2596 copywriting-correct.js.org
  cnames_active.js
Labels: add, project, user

#2597 nativemodels.js.org
  cnames_active.js
Labels: add, project, user

#2598 uppload.js.org
  cnames_active.js
Labels: add, organisation, project

#2599 battle-city.js.org
  cnames_active.js
Labels: add, project, user

#2600 ahegao.js.org / ege.js.org
  cnames_active.js
Labels: project, remove, user

#2602 zachmurphy.js.org
  cnames_active.js
Labels: add, user

#2603 yizao.js.org
  cnames_active.js
Labels: add, user

#2605 fullscreen.js.org
  cnames_active.js
Labels: add, project, user

#2606 vue-land.js.org
  cnames_active.js
Labels: change, external page

#2604 jacob-ebey.js.org
  cnames_active.js
Labels: add, user

#2609 ma124.js.org
  cnames_active.js
Labels: add, external page

#2608 README badges: Normalise paypal color, add PRs
  README.md
Labels: enhancement

#2610 manu.js.org
  cnames_active.js
Labels: add, project, user

#2612 karl.js.org
  cnames_active.js
Labels: SSL, change, project

#2613 guineapigbot.js.org
  cnames_active.js
Labels: add, project, provisional content

#2615 victor.js.org
  cnames_active.js
Labels: add, project, user

#2616 battlecry.js.org
  cnames_active.js
Labels: add, external page

#2617 Assorted fixes to cnames_active.js
  cnames_active.js
Labels: enhancement

#2618 Use new repo location
  404.html
  index.html
Labels: enhancement

#2620 woodsman.js.org
  cnames_active.js
Labels: add, project, user

#2622 spacebot.js.org
  cnames_active.js
Labels: add, user

#2621 wthunting.js.org
  cnames_active.js
Labels: add, project, user

#2624 lineup.js.org | lineupengine.js.org
  cnames_active.js
Labels: change, organisation, project

#2623 pixxel.js.org
  cnames_active.js
Labels: add, organisation

#2626 fre.js.org
  cnames_active.js
Labels: add, project, user

#2630 instant.js.org
  cnames_active.js
Labels: add, organisation

#2629 v-decorators.js.org
  cnames_active.js
Labels: add, external page

#2627 aziz.js.org
  cnames_active.js
Labels: add, bug, user

#2628 c.js.org
  cnames_active.js
Labels: add, user

#2631 tictactoe.js.org
  cnames_active.js
Labels: add, project, user

#2632 mi.js.org
  cnames_active.js
Labels: add, user

#2635 resources.js.org
  cnames_active.js
Labels: add, project, user

#2634 youtube-lite.js.org
  cnames_active.js
Labels: add, project, user

#2637 vue-coffee.js.org
  cnames_active.js
Labels: add, external page

#2639 topbot.js.org
  cnames_active.js
Labels: add, project, user

#2642 pretty-print-json.js.org
  cnames_active.js
Labels: add, organisation, project

#2641 jcord.js.org
  cnames_active.js
Labels: add, project, user

#2640 odin.js.org
  cnames_active.js
Labels: add, organisation, project

#2657 kolly.js.org
  cnames_active.js
Labels: add, project, user

#2658 outdoors.js.org
  cnames_active.js
Labels: add, project, provisional content, user
