Repository js-org/js.org, pull requests merged in 2018-03, with the labels that each got.

#1812 coord.js.org
  cnames_active.js
Labels: add, bug, project, user

#1813 batch-cluster.js.org
  cnames_active.js
Labels: add, project, user

#1814 funfuncs.js.org
  cnames_active.js
Labels: add, project, provisional content, user

#1815 salvattore.js.org
  cnames_active.js
Labels: add, project, user

#1818 crownstudios.js.org
  cnames_active.js
Labels: add, project, user

#1820 discunit.js.org
  cnames_active.js
Labels: add, project, user

#1821 octo.js.org
  cnames_active.js
Labels: add, project, user

#1817 exiftool-vendored.js.org
  cnames_active.js
Labels: add, project, user

#1822 producify.js.org
  cnames_active.js
Labels: add, project, user

#1823 boiler.js.org
  cnames_active.js
Labels: add, project, user

#1826 lightfair.js.org
  cnames_active.js
Labels: project, remove, user

#1827 bash.js.org
  cnames_active.js
Labels: SSL, change

#1824 zty.js.org
  cnames_active.js
Labels: add, user

#1829 mhsupport.js.org
  cnames_active.js
Labels: add, project, user

#1830 bunjil.js.org
  cnames_active.js
Labels: add, external page

#1831 delet.js.org
  cnames_active.js
Labels: add, organisation, project, provisional content

#1832 miscord.js.org
  cnames_active.js
Labels: add, project, user

#1828 react-static.js.org
  cnames_active.js
Labels: add, external page, invalid

#1833 smartquotes.js.org
  cnames_active.js
Labels: add, project, user

#1834 accordion.js.org
  cnames_active.js
Labels: add, project, user

#1835 miscord.js.org
  cnames_active.js
Labels: SSL, change

#1836 plexr.js.org
  cnames_active.js
Labels: add, organisation

#1841 food.js.org
  cnames_active.js
Labels: add, project, user

#1842 openrecord.js.org
  cnames_active.js
Labels: add, project, user

#1843 salvacam.js.org
  cnames_active.js
Labels: add, user

#1844 dhruvdutt.js.org
  cnames_active.js
Labels: add, user

#1845 Clean duplicate key
  cnames_active.js
Labels: enhancement

#1848 vue-treeselect.js.org
  cnames_active.js
Labels: add, project, user

#1850 serviceberry.js.org
  cnames_active.js
Labels: add, project, user

#1852 bob.js.org
  cnames_active.js
Labels: add, user

#1849 vuikit.js.org
  cnames_active.js
Labels: change, project

#1851 react-observatory.js.org
  cnames_active.js
Labels: add, external page, invalid

#1854 andre.js.org
  cnames_active.js
Labels: change, user

#1855 pastate.js.org
  cnames_active.js
Labels: add, project, user

#1859 v-charts.js.org
  cnames_active.js
Labels: add, organisation, project

#1847 marked.js.org
  cnames_active.js
Labels: add, invalid, organisation, project

#1860 jsonapi.js.org
  cnames_active.js
Labels: add, project, user

#1861 canvasconstructor.js.org
  cnames_active.js
Labels: add, project, user

#1862 razod.js.org
  cnames_active.js
Labels: add, user

#1864 awk.js.org / grep.js.org / sed.js.org
  cnames_active.js
Labels: SSL, change

#1865 razod.js.org
  cnames_active.js
Labels: change, organisation, project

#1867 itunes-bridge.js.org
  cnames_active.js
Labels: add, project, user

#1868 buttermilk.js.org
  cnames_active.js
Labels: add, external page

#1871 cr.js.org
  cnames_active.js
Labels: add, project, user

#1873 organizeapi.js.org
  cnames_active.js
Labels: add, external page

#1875 klasy-eris.js.org
  cnames_active.js
Labels: add, project, user

#1856 lab.js.org
  cnames_active.js
Labels: name conflict

#1874 dungeon.js.org
  cnames_active.js
Labels: add, project, user

#1876 laue.js.org
  cnames_active.js
Labels: add, project, user

#1878 mehrad.js.org
  cnames_active.js
Labels: add, user

#1877 karolina-and-ryan.js.org
  cnames_active.js
Labels: add, project, user
