Repository js-org/js.org, pull requests merged in 2019-12, with the labels that each got.

#3574 dot.js.org
  cnames_active.js
Labels: change, organisation, project

#3576 newyear.js.org
  cnames_active.js
Labels: add, project, user

#3580 starterbot.js.org
  cnames_active.js
Labels: external page, remove

#3579 bui.js.org
  cnames_active.js
Labels: add, project, user

#3578 alphabetify.js.org
  cnames_active.js
Labels: add, project, user

#3577 villain.js.org
  cnames_active.js
Labels: add, project, user

#3575 alyreza.js.org
  cnames_active.js
Labels: no content

#3582 rva.js.org
  cnames_active.js
Labels: add, project, user

#3586 dot-microservices.js.org / dot.js.org
  cnames_active.js
Labels: change, organisation, project

#3585 hltvbot.js.org
  cnames_active.js
Labels: add, project, user

#3587 dora.js.org
  cnames_active.js
Labels: add, organisation, project

#3588 switchjoy.js.org
  cnames_active.js
Labels: add, organisation

#3589 reatom.js.org
  cnames_active.js
Labels: add, project, user

#3590 lucy.js.org
  cnames_active.js
Labels: add, organisation

#3591 n.js.org
  cnames_active.js
Labels: add, project, user

#3595 conglo.js.org
  cnames_active.js
Labels: add, project, user

#3596 god.js.org
  cnames_active.js
Labels: add, user

#3598 hiven.js.org
  cnames_active.js
Labels: add, organisation, project

#3600 soofik.js.org
  cnames_active.js
Labels: add, user

#3601 ceruttimaicon.js.org
  cnames_active.js
Labels: add, user

#3604 bassdrum.js.org
  cnames_active.js
Labels: add, project, user

#3605 ali.js.org
  cnames_active.js
Labels: change, external page, user

#3607 hilo3d.js.org
  cnames_active.js
Labels: add, organisation, project

#3556 ember-electron.js.org
  cnames_active.js
Labels: change, organisation, project

#3609 bo.js.org
  cnames_active.js
Labels: add, project, user

#3614 jonny.js.org
  cnames_active.js
Labels: add, project, user

#3613 mitu.js.org
  cnames_active.js
Labels: add, project, user

#3612 redux-undo.js.org
  cnames_active.js
Labels: change, external page

#3615 awesometech10.js.org
  cnames_active.js
Labels: add, user

#3611 twcopy.js.org
  cnames_active.js
Labels: add, project, user

#3619 JS.ORG CLEANUP (#3554)
  cnames_active.js
Labels: important, remove

#3620 phasors-demo.js.org
  cnames_active.js
Labels: add, project, user

#3622 bo.js.org
  cnames_active.js
Labels: change, project, user

#3623 ahmeterdgn.js.org
  cnames_active.js
Labels: add, user

#3625 jonstonchan.js.org
  cnames_active.js
Labels: add, external page

#3626 pencil.js.org
  cnames_active.js
Labels: add, organisation, project
