Repository js-org/js.org, pull requests merged in 2021-12, with the labels that each got.

#6666 naja.js.org
  cnames_active.js
Labels: organisation, project, change

#6669 itemszop.js.org
  cnames_active.js
Labels: add, user, project

#6672 liguori.js.org
  cnames_active.js
Labels: user, remove

#6673 lbox.js.org
  cnames_active.js
Labels: add, organisation

#6677 simple-pip.js.org
  cnames_active.js
Labels: user, project, change

#6676 gba.js.org
  cnames_active.js
Labels: add, user, project

#6680 gametime.js.org
  cnames_active.js
Labels: add, user, project

#6683 charliez0.js.org
  cnames_active.js
Labels: change, external page

#6685 use-cookie-consent.js.org
  cnames_active.js
Labels: add, organisation, project

#6689 kokkoro.js.org
  cnames_active.js
Labels: organisation, change

#6690 relic.js.org
  cnames_active.js
Labels: add, organisation

#6692 garlic-team.js.org
  cnames_active.js
Labels: add, organisation, project

#6696 foca.js.org
  cnames_active.js
Labels: add, organisation, project

#6697 disdai.js.org
  cnames_active.js
Labels: organisation, project, change

#6699 daisy.js.org
  cnames_active.js
Labels: user, project, change

#6700 groupme.js.org
  cnames_active.js
Labels: organisation, project, change

#6701 yt-quota-manager.js.org
  cnames_active.js
Labels: add, user, project

#6702 gba.js.org
  cnames_active.js
Labels: user, project, change

#6705 fov.js.org
  cnames_active.js
Labels: add, user, project

#6706 demirdb.js.org
  cnames_active.js
Labels: user, project, change

#6707 zaman.js.org
  cnames_active.js
Labels: user, project, change

#6712 simplyeco.js.org
  cnames_active.js
Labels: add, user, project

#6718 coolnavs.js.org
  cnames_active.js
Labels: add, user, project

#6720 costro.js.org
  cnames_active.js
Labels: add, organisation

#6721 fmkli.js.org
  cnames_active.js
Labels: change, external page

#6724 gaiman.js.org
  cnames_active.js
Labels: add, user, project

#6725 atils.js.org
  cnames_active.js
Labels: add, user, project

#6729 audio-captcha.js.org
  cnames_active.js
Labels: add, user, project

#6726 git-terminal.js.org
  cnames_active.js
Labels: add, user, project

#6731 mobbler.js.org
  cnames_active.js
Labels: add, user, project

#6734 Cleanup: Perfect Format & Sorting
  cnames_active.js
Labels: enhancement

#6735 usedapp.js.org
  cnames_active.js
Labels: add, user, project

#6732 1host.js.org
  cnames_active.js
Labels: organisation, remove

#6740 densewaire.js.org
  cnames_active.js
Labels: add, user, project, remove

#6739 lifetime-countdown.js.org
  cnames_active.js
Labels: add, user, project

#6745 tts.js.org
  cnames_active.js
Labels: add, user, project

#6742 million.js.org
  cnames_active.js
Labels: change, external page

#6749 base62.js.org
  cnames_active.js
Labels: add, organisation, project

#6748 passphrase.js.org
  cnames_active.js
Labels: add, organisation, project

#6751 selectre.js.org
  cnames_active.js
Labels: add, user, project

#6750 erebus.js.org
  cnames_active.js
Labels: add, organisation, project

#6754 yurd.js.org
  cnames_active.js
Labels: add, user, project

#6755 frost.js.org
  cnames_active.js
Labels: organisation, project, change

#6756 discord-button-page.js.org
  cnames_active.js
Labels: add, user, project
