Repository js-org/js.org, pull requests merged in 2022-11, with the labels that each got.

#7769 Update README.md
  README.md
Labels: enhancement

#7778 craco.js.org
  cnames_active.js
Labels: add, user, project

#7779 ts-dax.js.org
  cnames_active.js
Labels: add, user, project

#7781 bright.js.org
  cnames_active.js
Labels: add, organisation

#7782 nashi.js.org
  cnames_active.js
Labels: add, external page

#7784 crls.js.org
  cnames_active.js
Labels: add, user, project

#7785 wolvesville.js.org
  cnames_active.js
Labels: add, organisation, project

#7790 coinflip.js.org
  cnames_active.js
Labels: change, external page

#7792 connect.stacks.js.org
  cnames_active.js
Labels: add, external page

#7804 next-qrcode.js.org
  cnames_active.js
Labels: add, user, project

#7805 canvasui.js.org
  cnames_active.js
Labels: user, project, remove

#7803 alova.js.org
  cnames_active.js
Labels: add, organisation

#7809 canvasui.js.org
  cnames_active.js
Labels: add, organisation

#7812 antdocs.js.org
  cnames_active.js
Labels: add, external page

#7818 antdocs.js.org
  cnames_active.js
Labels: change, external page

#7819 pagelike.js.org
  cnames_active.js
Labels: add, user, project

#7822 infrpg.js.org
  cnames_active.js
Labels: add, external page

#7826 revurn.js.org
  cnames_active.js
Labels: add, organisation

#7827 infrpg.js.org
  cnames_active.js
Labels: change, external page, awaiting response

#7828 erdem.js.org / erdems.js.org
  cnames_active.js
Labels: user, change

#7835 hashparser.js.org
  cnames_active.js
Labels: add, user, project

#7829 hindenburg.js.org
  cnames_active.js
Labels: add, organisation, project

#7836 moonlink.js.org
  cnames_active.js
Labels: change, external page, awaiting response

#7837 coinflip.js.org
  cnames_active.js
Labels: user, project, change, external page

#7839 divifier.js.org
  cnames_active.js
Labels: add, user, project

#7841 custard.js.org
  cnames_active.js
Labels: add, organisation

#7847 gemstone.js.org
  cnames_active.js
Labels: add, user, project
