Repository js-org/js.org, pull requests merged in 2022-05, with the labels that each got.

#7223 spx.js.org
  cnames_active.js
Labels: add, external page

#7226 hiddenfrombots.js.org
  cnames_active.js
Labels: add, external page

#7228 condition.js.org
  cnames_active.js
Labels: user, project, remove

#7227 filter.js.org
  cnames_active.js
Labels: add, user, project

#7229 statisfy.js.org
  cnames_active.js
Labels: add, organisation, project

#7231 discord-portable-player.js.org
  cnames_active.js
Labels: add, user, project

#7233 satori.js.org
  cnames_active.js
Labels: add, organisation

#7234 canvg.js.org
  cnames_active.js
Labels: add, organisation, project

#7242 guildeno.js.org
  cnames_active.js
Labels: add, organisation, project

#7237 splendid.js.org
  cnames_active.js
Labels: add, organisation, project

#7251 djs-application-commands.js.org
  cnames_active.js
Labels: add, external page

#7254 document-scanner.js.org
  cnames_active.js
Labels: add, organisation, project

#7256 angular-mfe.js.org
  cnames_active.js
Labels: add, organisation, project, provisional content

#7262 vue-magnifier.js.org
  cnames_active.js
Labels: add, organisation, project

#7269 vue-auth3.js.org
  cnames_active.js
Labels: add, user, project

#7270 hesperus.js.org
  cnames_active.js
Labels: add, organisation, project

#7271 whatscode.js.org
  cnames_active.js
Labels: add, user, project

#7273 disdai.js.org
  cnames_active.js
Labels: organisation, project, remove

#7274 canvasui.js.org
  cnames_active.js
Labels: user, project, remove

#7272 discord-easy-leveling.js.org
  cnames_active.js
Labels: add, user, project

#7277 oem.js.org
  cnames_active.js
Labels: add, user, project

#7283 discord-rest.js.org
  cnames_active.js
Labels: add, user, project, awaiting CNAME

#7289 scadies.js.org
  cnames_active.js
Labels: add, external page

#7288 ree.js.org
  cnames_active.js
Labels: add, organisation, project

#7295 crossani.js.org
  cnames_active.js
Labels: add, external page
