Repository js-org/js.org, pull requests merged in 2022-10, with the labels that each got.

#7666 guildedbot.js.org
  cnames_active.js
Labels: add, user, project, error

#7671 chatapp.js.org
  cnames_active.js
Labels: user, project, remove

#7677 mailbox.js.org
  cnames_active.js
Labels: add, user, project

#7681 dismord.js.org
  cnames_active.js
Labels: add, organisation, project

#7679 guildedbot.js.org / guide.guildedbot.js.org
  cnames_active.js
Labels: add, organisation, project, change, external page

#7684 base-classes.js.org
  cnames_active.js
Labels: add, user, project

#7685 hereby.js.org
  cnames_active.js
Labels: add, user, project

#7687 webos.js.org
  cnames_active.js
Labels: add, user, project

#7692 create-djs-app.js.org
  cnames_active.js
Labels: add, external page

#7696 pcl.js.org
  cnames_active.js
Labels: add, external page

#7700 data-dashboard.js.org / dna.js.org
  cnames_active.js
Labels: organisation, project, change

#7701 testio.js.org
  cnames_active.js
Labels: add, user, project

#7715 comfortable.js.org
  cnames_active.js
Labels: add, user, project

#7714 guildedts.js.org / docs.guildedts.js.org
  cnames_active.js
Labels: add, organisation, project, change, external page

#7718 spark-handler.js.org
  cnames_active.js
Labels: add, external page

#7719 shiro.js.org
  cnames_active.js
Labels: add, user, project

#7725 react-comfort.js.org
  cnames_active.js
Labels: add, user, project

#7726 alveron.js.org
  cnames_active.js
Labels: user, project, change, external page

#7728 frontik.js.org
  cnames_active.js
Labels: add, user, project

#7727 carrier.js.org
  cnames_active.js
Labels: add, user, project

#7739 py-like.js.org
  cnames_active.js
Labels: add, user, project

#7742 actions-creator.js.org
  cnames_active.js
Labels: add, user, project

#7753 jstyle.js.org
  cnames_active.js
Labels: add, user, project

#7744 snowbox.js.org
  cnames_active.js
Labels: add, user, project

#7765 ringo.js.org
  cnames_active.js
Labels: add, external page, awaiting CNAME

#7767 twitch.js.org
  cnames_active.js
Labels: organisation, project, change

#7770 ankareport.js.org
  cnames_active.js
Labels: add, organisation
