Repository js-org/js.org, pull requests merged in 2022-06, with the labels that each got.

#7304 crossani.js.org
  cnames_active.js
Labels: change, external page

#7305 disgroupdev.js.org
  cnames_active.js
Labels: add, organisation, project

#7308 easiermongo.js.org
  cnames_active.js
Labels: add, user, project

#7310 music.js.org
  cnames_active.js
Labels: add, user, project

#7311 piano.js.org
  cnames_active.js
Labels: add, user, project

#7313 illustrator.js.org
  cnames_active.js
Labels: add, external page

#7307 registry.flightpkg.js.org
  cnames_active.js
Labels: add, external page

#7322 zaman.js.org
  cnames_active.js
Labels: user, project, remove

#7321 purplet.js.org
  cnames_active.js
Labels: add, external page

#7328 pwaga.js.org
  cnames_active.js
Labels: add, user, project

#7339 cy-rn.js.org
  cnames_active.js
Labels: add, user, project

#7345 30dayjavascript.js.org
  cnames_active.js
Labels: add, external page

#7347 aries.js.org
  cnames_active.js
Labels: add, organisation, project

#7357 sociably.js.org
  cnames_active.js
Labels: add, organisation, project

#7359 disgrowth.js.org
  cnames_active.js
Labels: add, user, project

#7360 discord-kommando.js.org
  cnames_active.js
Labels: add, organisation, project

#7361 what-version-of-node.js.org
  cnames_active.js
Labels: add, user, project

#7365 cooler.js.org
  cnames_active.js
Labels: add, external page

#7370 remove disgrowth.js.org / add disgrow.js.org
  cnames_active.js
Labels: add, user, project, remove

#7372 caliph-api.js.org
  cnames_active.js
Labels: invalid
