Repository js-org/js.org, pull requests merged in 2023-10, with the labels that each got.

#8548 dreamcord.js.org
  cnames_active.js
Labels: add, organisation, project

#8554 mctrl.js.org
  cnames_active.js
Labels: add, external page

#8559 e-query.js.org
  cnames_active.js
Labels: add, user, project

#8561 xterminal.js.org
  cnames_active.js
Labels: add, user, project

#8566 playground.blu.js.org
  cnames_active.js
Labels: user, project, remove

#8567 nostalgist.js.org
  cnames_active.js
Labels: add, user, project

#8571 canvasui.js.org
  cnames_active.js
Labels: organisation, project, change

#8573 esboot.js.org
  cnames_active.js
Labels: add, user, project, provisional content

#8574 iphw.js.org
  cnames_active.js
Labels: add, user, project

#8575 promethium.js.org
  cnames_active.js
Labels: add, organisation, project

#8582 zyx.js.org
  cnames_active.js
Labels: add, external page

#8583 aesthetic.js.org
  cnames_active.js
Labels: add, external page

#8588 react-dnd-cn.js.org
  cnames_active.js
Labels: user, project, change, external page

#8589 react-fluent-cn.js.org
  cnames_active.js
Labels: remove, external page

#8591 csur.js.org
  cnames_active.js
Labels: add, provisional content, external page

#8592 magickwand.js.org
  cnames_active.js
Labels: add, user, project

#8594 learn.js.org
  cnames_active.js
Labels: add, organisation, project

#8593 ambush.js.org
  cnames_active.js
Labels: add, organisation, project

#8596 denepo.js.org
  cnames_active.js
Labels: add, organisation, project, provisional content

#8597 bunicorn.js.org
  cnames_active.js
Labels: add, user, project

#8601 oslo.js.org
  cnames_active.js
Labels: add, user, project

#8604 lazy.js.org
  cnames_active.js
Labels: add, user, project

#8608 kotori.js.org
  cnames_active.js
Labels: add, organisation, project

#8609 linemapper.js.org
  cnames_active.js
Labels: add, user, project

#8612 neureact.js.org
  cnames_active.js
Labels: add, user, project
