Repository js-org/js.org, pull requests merged in 2023-08, with the labels that each got.

#8420 typedi.js.org
  cnames_active.js
Labels: add, user, project

#8422 bilioutils.js.org
  cnames_active.js
Labels: add, user, project

#8423 msemoji.js.org
  cnames_active.js
Labels: add, user, project

#8425 oxi.js.org
  cnames_active.js
Labels: add, external page

#8428 use-bootstrap.js.org / use-bootstrap-select.js.org
  cnames_active.js
Labels: add, user, project

#8433 use-bootstrap-tag.js.org
  cnames_active.js
Labels: add, organisation, project

#8437 spyter.js.org
  cnames_active.js
Labels: add, external page

#8435 fanbook-api-sdk.js.org
  cnames_active.js
Labels: add, organisation, project

#8443 isadb.js.org
  cnames_active.js
Labels: add, user, project, awaiting CNAME

#8449 lisk-did.js.org
  cnames_active.js
Labels: add, user, project

#8452 megdb.js.org
  cnames_active.js
Labels: invalid

#8463 agrume.js.org
  cnames_active.js
Labels: add, external page

#8460 note.js.org
  cnames_active.js
Labels: add, external page

#8465 calcium.js.org
  cnames_active.js
Labels: add, external page

#8466 riffy.js.org
  cnames_active.js
Labels: change, external page
