Repository js-org/js.org, pull requests merged in 2023-02, with the labels that each got.

#7970 polona.js.org
  cnames_active.js
Labels: add, user, project, provisional content

#7976 lychee.js.org
  cnames_active.js
Labels: organisation, project, change

#7981 cdb.js.org
  cnames_active.js
Labels: organisation, remove

#7980 lunisolar.js.org & colorsea.js.org
  cnames_active.js
Labels: add, user, project

#7997 kiai.js.org
  cnames_active.js
Labels: add, organisation, project

#7996 reciple.js.org
  cnames_active.js
Labels: change, external page

#8001 niplayer.js.org
  cnames_active.js
Labels: add, user, project

#8011 fy.js.org
  cnames_active.js
Labels: add, provisional content, external page

#8004 moonlightdb.js.org
  cnames_active.js
Labels: add, external page

#8015 JS.ORG CLEANUP (#7929)
  cnames_active.js
Labels: remove, enhancement

#8023 reager.js.org
  cnames_active.js
Labels: add, user, project, provisional content

#8025 seia.js.org
  cnames_active.js
Labels: add, organisation, project

#8035 phylum.js.org
  cnames_active.js
Labels: organisation, remove

#8038 turboprisma.js.org
  cnames_active.js
Labels: add, provisional content, external page

#8040 pixiv.js.org
  cnames_active.js
Labels: awaiting response

#8034 xchart.js.org
  cnames_active.js
Labels: add, external page

#8044 space.js.org
  cnames_active.js
Labels: add, user, project

#8047 quickdb.js.org
  cnames_active.js
Labels: organisation, project, change, external page

#8048 newcar.js.org
  cnames_active.js
Labels: add, external page

#8049 react-starport.js.org
  cnames_active.js
Labels: change, external page
