Repository js-org/js.org, pull requests merged in 2024-05, with the labels that each got.

#8977 backupie.js.org
  cnames_active.js
Labels: add, user, project

#8976 exome.js.org
  cnames_active.js
Labels: add, external page

#8983 surgio.js.org
  cnames_active.js
Labels: change, external page

#8981 cap.js.org
  cnames_active.js
Labels: add, organisation, project

#8987 solitude.js.org
  cnames_active.js
Labels: add, external page

#8985 sign-poc.js.org
  cnames_active.js
Labels: add, user, project

#8984 Improve + clean up README
  README.md
Labels: enhancement

#8994 svr.js.org
  cnames_active.js
Labels: user, project, remove

#8995 openkey.js.org
  cnames_active.js
Labels: add, organisation, project

#8996 browserless.js.org
  cnames_active.js
Labels: organisation, project, change

#8992 uneventful.js.org
  cnames_active.js
Labels: add, user, project

#8998 auto-immutable.js.org
  cnames_active.js
Labels: add, organisation, project

#9002 micanto.js.org
  cnames_active.js
Labels: add, organisation, project

#9006 bukumark.js.org
  cnames_active.js
Labels: add, user, project

#9010 flaregram.js.org
  cnames_active.js
Labels: add, user, project

#9024 nexbase-core.js.org
  cnames_active.js
Labels: add, user, project, provisional content

#9022 calisto.js.org
  cnames_active.js
Labels: add, external page

#9040 kkna.js.org
  cnames_active.js
Labels: add, organisation, project

#9044 lisk-did.js.org / klayr-did.js.org
  cnames_active.js
Labels: add, user, project, remove

#9052 sidewind.js.org
  cnames_active.js
Labels: change, external page

#9057 tclock.js.org
  cnames_active.js
Labels: add, user, project

#9064 icecream.js.org
  cnames_active.js
Labels: add, organisation, project
