Repository js-org/js.org, pull requests merged in 2024-04, with the labels that each got.

#8935 rebornxp.js.org
  cnames_active.js
Labels: change, external page

#8938 freegpt.js.org
  cnames_active.js
Labels: user, project, change

#8940 diabolo.js.org
  cnames_active.js
Labels: add, external page

#8942 poru.js.org
  cnames_active.js
Labels: change, external page

#8943 warlock.js.org
  cnames_active.js
Labels: add, user, project

#8945 sjpm.js.org
  cnames_active.js
Labels: awaiting response, awaiting CNAME

#8948 trackymouse.js.org
  cnames_active.js
Labels: add, user, project

#8952 vega.js.org
  cnames_active.js
Labels: add, external page

#8953 use-bootstrap-toaster.js.org
  cnames_active.js
Labels: add, user, project

#8955 skyware.js.org
  cnames_active.js
Labels: organisation, project, change, SSL

#8961 ht.js.org
  cnames_active.js
Labels: add, user, project

#8962 snip.js.org
  cnames_active.js
Labels: add, external page

#8967 hypixel.js.org
  cnames_active.js
Labels: change, external page

#8970 frui.js.org
  cnames_active.js
Labels: add, organisation, project

#8971 extension.js.org
  cnames_active.js
Labels: add, user, project

#8973 integro.js.org
  cnames_active.js
Labels: add, user, project

#8978 tsx-browser-compiler.js.org
  cnames_active.js
Labels: add, user, project
