Repository js-org/js.org, pull requests merged in 2024-08, with the labels that each got.

#9169 imvu.js.org
  cnames_active.js
Labels: add, external page

#9177 reactflow-cn.js.org
  cnames_active.js
Labels: add, external page

#9173 brazil.js.org
  cnames_active.js
Labels: add, organisation, project

#9182 krds.js.org
  cnames_active.js
Labels: add, organisation, project

#9188 nostr.js.org
  cnames_active.js
Labels: add, user, project

#9190 webbuild.js.org
  cnames_active.js
Labels: add, user, project

#9191 codemirror-languageservice.js.org
  cnames_active.js
Labels: add, external page

#9201 kun.js.org
  cnames_active.js
Labels: add, user, project

#9202 graffle.js.org
  cnames_active.js
Labels: add, user, project

#9204 abi.js.org
  cnames_active.js
Labels: add, organisation

#9203 tik.js.org
  cnames_active.js
Labels: add, user, project

#9206 radashi.js.org
  cnames_active.js
Labels: add, organisation

#9212 ddnet.js.org
  cnames_active.js
Labels: add, user, project

#9211 go.js.org
  cnames_active.js
Labels: add, organisation, project

#9214 xdtoast.js.org
  cnames_active.js
Labels: add, user, project

#9215 pulsy.js.org
  cnames_active.js
Labels: add, user, project

#9216 avg.js.org
  cnames_active.js
Labels: add, user, project
