Repository js-org/js.org, pull requests merged in 2024-10, with the labels that each got.

#9298 remove nuclear.js.org
  cnames_active.js
Labels: user, project, remove

#9299 cssfun.js.org
  cnames_active.js
Labels: add, user, project

#9304 wifidrop.js.org
  cnames_active.js
Labels: add, user, project

#9313 puzzle.js.org
  cnames_active.js
Labels: invalid

#9318 js2lua.js.org
  cnames_active.js
Labels: add, user, project

#9321 storybook.js.org
  cnames_active.js
Labels: change, external page

#9329 byteforge.js.org
  cnames_active.js
Labels: add, user, project

#9326 olova.js.org
  cnames_active.js
Labels: add, external page

#9330 aoimysql.js.org
  cnames_active.js
Labels: add, external page

#9331 akar.js.org
  cnames_active.js
Labels: add, user, project

#9334 passkeys.js.org
  cnames_active.js
Labels: add, organisation, project

#9337 sissi.js.org
  cnames_active.js
Labels: add, organisation, project

#9338 better-upload.js.org
  cnames_active.js
Labels: add, external page

#9342 tgx-core.js.org
  cnames_active.js
Labels: add, organisation, project

#9341 lua2js.js.org
  cnames_active.js
Labels: add, user, project

#9340 model.js.org
  cnames_active.js
Labels: add, user, project

#9343 lazyload.js.org
  cnames_active.js
Labels: add, user, project

#9348 dv-scalebar.js.org
  cnames_active.js
Labels: add, user, project

#9349 better-upload.js.org
  cnames_active.js
Labels: change, external page

#9353 bathtiles.js.org
  cnames_active.js
Labels: add, user, project
