Repository js-org/js.org, pull requests merged in 2025-07, with the labels that each got.

#9929 open-api.js.org
  cnames_active.js
Labels: add, user, project

#9951 Remove shebang.js.org
  ns_active.js
Labels: remove, NS

#9957 welson.js.org
  cnames_active.js
Labels: add, user, project

#9972 typeorm-pino-logger.js.org
  cnames_active.js
Labels: add, user, project

#9967 yurba.js.org
  cnames_active.js
Labels: add, external page

#9989 msemoji.js.org
  cnames_active.js
Labels: user, project, change

#9994 codetwix.js.org
  cnames_active.js
Labels: add, user, project, awaiting response

#9995 gitnifty.js.org
  cnames_active.js
Labels: add, user, project

#10001 textstorage.js.org
  cnames_active.js
Labels: add, user, project

#10002 profilie.js.org
  cnames_active.js
Labels: add, organisation

#10011 ghost-shell.js.org
  cnames_active.js
Labels: add, user, project

#10024 zare.js.org
  cnames_active.js
Labels: add, user, project

#10025 ko.mobx.js.org & zh.mobx.js.org
  cnames_active.js
Labels: add, external page

#10030 surgio.js.org
  cnames_active.js
Labels: change, external page

#10033 create-ts-fast.js.org
  cnames_active.js
Labels: add, user, project
