Repository js-org/js.org, pull requests merged in 2025-08, with the labels that each got.

#10038 stax.js.org
  cnames_active.js
Labels: add, external page

#10040 grambulate.js.org
  cnames_active.js
Labels: add, user, project

#10039 esdora.js.org
  cnames_active.js
Labels: add, organisation

#10053 jimple.js.org
  cnames_active.js
Labels: add, user, project

#10055 Removing inactive NS records
  ns_active.js
Labels: remove, NS

#10073 agentify.js.org
  cnames_active.js
Labels: add, organisation, project

#10075 chatgpt.js.org
  cnames_active.js
Labels: add, organisation, project

#10081 t8.js.org
  cnames_active.js
Labels: add, organisation

#10082 mobileconfiginstaller.js.org
  cnames_active.js
Labels: add, user, project

#10096 teamspeak.js.org
  cnames_active.js
Labels: add, organisation, project

#10102 xiangyue.js.org
  cnames_active.js
Labels: add, user, project

#10103 neteasecloudmusicapienhanced.js.org
  cnames_active.js
Labels: add, organisation, project

#10104 guida.js.org
  cnames_active.js
Labels: add, external page

#10110 codeshare.js.org
  cnames_active.js
Labels: remove, external page

#10109 just.js.org
  cnames_active.js
Labels: add, organisation
