Repository js-org/js.org, pull requests merged in 2025-01, with the labels that each got.

#9474 genpass.js.org
  cnames_active.js
Labels: add, organisation, project

#9478 drawie.js.org
  cnames_active.js
Labels: add, external page

#9483 lrclib.js.org
  cnames_active.js
Labels: add, user, project

#9488 domxy.js.org
  cnames_active.js
Labels: add, user, project

#9489 tech-human-id.js.org
  cnames_active.js
Labels: add, user, project

#9490 agenda-tech-brasil-site.js.org
  cnames_active.js
Labels: add, user, project

#9495 foxogram.js.org
  cnames_active.js
Labels: add, external page

#9497 yay-machine.js.org
  cnames_active.js
Labels: add, user, project

#9498 air.js.org
  cnames_active.js
Labels: add, organisation, project

#9499 mcstatus.js.org
  cnames_active.js
Labels: remove, external page

#9501 atos.js.org
  cnames_active.js
Labels: add, user, project

#9509 lizzy.js.org
  cnames_active.js
Labels: add, user, project

#9511 atos.js.org
  cnames_active.js
Labels: change, external page

#9508 libh.js.org
  cnames_active.js
Labels: add, user, project, error

#9467 codeshare.js.org
  cnames_active.js
Labels: add, external page, error

#9514 diya.js.org
  cnames_active.js
Labels: add, external page

#9517 plain-blog.js.org
  cnames_active.js
Labels: add, user, project

#9516 get.js.org / hx.js.org / status-hx.js.org
  cnames_active.js
Labels: change, external page

#9524 ws-debug.js.org
  cnames_active.js
Labels: change, SSL

#9533 libcurl.js.org
  cnames_active.js
Labels: add, external page
