Repository js-org/js.org, pull requests merged in 2025-05, with the labels that each got.

#9747 crcalc.js.org
  cnames_active.js
Labels: add, user, project

#9754 datamanager.js.org
  cnames_active.js
Labels: add, user, project

#9763 enn.js.org
  cnames_active.js
Labels: add, user, project

#9768 doom.js.org
  cnames_active.js
Labels: add, organisation, project

#9769 comptime.js.org
  cnames_active.js
Labels: add, organisation, project

#9761 salary.js.org
  cnames_active.js
Labels: add, user, project

#9779 clipx.js.org
  cnames_active.js
Labels: add, external page

#9777 surrealorm.js.org
  cnames_active.js
Labels: add, external page

#9782 Add CI Check for Validating PR Template
  .github/workflows/validate.yml
Labels: enhancement, CI IMP

#9788 react-wheel-picker.js.org
  cnames_active.js
Labels: add, external page

#9792 pa.js.org
  cnames_active.js
Labels: add, user, project, provisional content

#9799 docsify-sitemap.js.org
  cnames_active.js
Labels: add, organisation, project

#9801 impactminiblox.js.org
  cnames_active.js
Labels: add, user, project

#9803 statsmonit.js.org
  cnames_active.js
Labels: add, user, project

#9810 grab.js.org
  cnames_active.js
Labels: add, user, project

#9814 social-sdk.js.org
  cnames_active.js
Labels: add, organisation, project

#9815 er-api-sdk.js.org
  cnames_active.js
Labels: add, organisation, project

#9820 hfsyun.js.org
  cnames_active.js
Labels: user, remove
